use_frameworks!

platform :ios, '9.0'

target 'CD_ObjC_Example' do
  pod 'CaamDauObjC/All', :path => '../'
  
  pod 'Home', :path => './Module/Home'

  target 'CD_ObjC_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    #pod 'FBSnapshotTestCase'
  end
end
